// 성경 66권 목록
export const BIBLE_BOOKS = [
  // 구약 39권
  { name: '창세기', category: '구약' },
  { name: '출애굽기', category: '구약' },
  { name: '레위기', category: '구약' },
  { name: '민수기', category: '구약' },
  { name: '신명기', category: '구약' },
  { name: '여호수아', category: '구약' },
  { name: '사사기', category: '구약' },
  { name: '룻기', category: '구약' },
  { name: '사무엘상', category: '구약' },
  { name: '사무엘하', category: '구약' },
  { name: '열왕기상', category: '구약' },
  { name: '열왕기하', category: '구약' },
  { name: '역대상', category: '구약' },
  { name: '역대하', category: '구약' },
  { name: '에스라', category: '구약' },
  { name: '느헤미야', category: '구약' },
  { name: '에스더', category: '구약' },
  { name: '욥기', category: '구약' },
  { name: '시편', category: '구약' },
  { name: '잠언', category: '구약' },
  { name: '전도서', category: '구약' },
  { name: '아가', category: '구약' },
  { name: '이사야', category: '구약' },
  { name: '예레미야', category: '구약' },
  { name: '예레미야애가', category: '구약' },
  { name: '에스겔', category: '구약' },
  { name: '다니엘', category: '구약' },
  { name: '호세아', category: '구약' },
  { name: '요엘', category: '구약' },
  { name: '아모스', category: '구약' },
  { name: '오바댜', category: '구약' },
  { name: '요나', category: '구약' },
  { name: '미가', category: '구약' },
  { name: '나훔', category: '구약' },
  { name: '하박국', category: '구약' },
  { name: '스바냐', category: '구약' },
  { name: '학개', category: '구약' },
  { name: '스가랴', category: '구약' },
  { name: '말라기', category: '구약' },
  // 신약 27권
  { name: '마태복음', category: '신약' },
  { name: '마가복음', category: '신약' },
  { name: '누가복음', category: '신약' },
  { name: '요한복음', category: '신약' },
  { name: '사도행전', category: '신약' },
  { name: '로마서', category: '신약' },
  { name: '고린도전서', category: '신약' },
  { name: '고린도후서', category: '신약' },
  { name: '갈라디아서', category: '신약' },
  { name: '에베소서', category: '신약' },
  { name: '빌립보서', category: '신약' },
  { name: '골로새서', category: '신약' },
  { name: '데살로니가전서', category: '신약' },
  { name: '데살로니가후서', category: '신약' },
  { name: '디모데전서', category: '신약' },
  { name: '디모데후서', category: '신약' },
  { name: '디도서', category: '신약' },
  { name: '빌레몬서', category: '신약' },
  { name: '히브리서', category: '신약' },
  { name: '야고보서', category: '신약' },
  { name: '베드로전서', category: '신약' },
  { name: '베드로후서', category: '신약' },
  { name: '요한일서', category: '신약' },
  { name: '요한이서', category: '신약' },
  { name: '요한삼서', category: '신약' },
  { name: '유다서', category: '신약' },
  { name: '요한계시록', category: '신약' },
]

export type BibleBook = typeof BIBLE_BOOKS[number]

